/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pattern;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void weatherStationHasObservators() {
        WeatherStation station = new WeatherStation();
        MobileWeatherDisplay mobileWeatherDisplay = new MobileWeatherDisplay(station);
        // how to test it? 
    }
}
